#!/usr/bin/python
import sys
import logging
from optparse import OptionParser
from mreplay.explorer import Explorer

def configure_logging(level=logging.DEBUG):
    logging.basicConfig(format="\033[0;33m%(levelname)s\033[m:%(message)s",
                        level=level, stream=sys.stderr)

def main():
    usage = 'usage: %prog [options] log_file'
    desc = 'Replay a previously recorded execution.'
    parser = OptionParser(usage=usage, description=desc)
    parser.add_option("-v", "--verbose",
            action="store_true", dest="verbose", default=False,
            help="Verbose output")
    parser.add_option("-f", "--on-the-fly",
            action="store_true", dest="on_the_fly", default=False,
            help="Use the on the fly optimization")
    parser.add_option("-x", "--var-io",
            action="store_true", dest="var_io", default=False,
            help="Don't force original read/write() buffer size")
    parser.add_option("-i", "--isolate",
            action="store_true", dest="isolate", default=False,
            help="Isolate the file system")
    parser.add_option("-l", "--linear",
            action="store_true", dest="linear", default=True,
            help="Use a linear scaling")
    parser.add_option("-s", "--num-success-stop",
            type="int", dest="num_success_to_stop", default=1,
            help="Stop after how many successes")

    parser.add_option("-a", "--add-constant",
            type="int", dest="add_constant", default=-1,
            help="Add constant")

    parser.add_option("-d", "--del-constant",
            type="int", dest="del_constant", default=-1,
            help="Del constant")

    parser.add_option("-m", "--match-constant",
            type="int", dest="match_constant", default=3,
            help="Match constant")

    parser.add_option("-D", "--max-delete",
            type="int", dest="max_delete", default=100,
            help="Max events to delete at once")

    parser.add_option("-F", "--max-on-the-fly",
            type="int", dest="max_otf", default=10000,
            help="Max events to add on the fly")

    parser.add_option("-p", "--pattern",
            dest="pattern", help="Replay pattern, *:replace, +: add, -:remove, .:default")

    (options, args) = parser.parse_args()
    if not args:
        parser.error('Give me a log file')
    if len(args) > 2:
        parser.error('You have extra arguments')
    logfile_path = args[0]

    configure_logging((logging.INFO, logging.DEBUG)[options.verbose])

    Explorer(logfile_path, options.on_the_fly, options.var_io,
             options.num_success_to_stop, options.isolate, options.linear,
             options.pattern, options.add_constant, options.del_constant,
             options.match_constant, options.max_delete, options.max_otf).run()

if __name__ == '__main__':
    main()
